name: CI/CD for php-docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and run Docker Compose
      run: |
        docker-compose up -d
        # Test if the main service is running
        docker-compose exec -T php-apache curl -f http://localhost:8080 || exit 1

    - name: Tear down Docker Compose
      run: docker-compose down
